### ISSUE TITLE
Preserve stacktrace of internal error

### ISSUE THREAD

**Issue by ianwalter** [pkosiec/mongo-seeding#119]
Hello, I'm wondering what the use case is for this:
https://github.com/pkosiec/mongo-seeding/blob/d51182447ea649de8cbf5183946425c1e8975118/core/src/index.ts#L145

The reason I ask is because, to me, it seems unnecessary and even detrimental to end-users like myself since it essentially discards the original error's stacktrace. I have some experience in dealing with errors in Node.js, perhaps I can help solve the original problem this is trying to solve?

Thank you for your open source work on this project!

**Comment by pkosiec** [comment]
Hi @ianwalter,

This is quite old piece of code not touched from a long time (like 2 years). Mongo Seeding CLI and core was the same codebase back then, if I recall it correctly.

The idea behind wrapping error was to, well, wrap the error and modify the error name and message saying that this is something related to Mongo Seeding. The long term idea was preparing different internal types of errors in the app (mostly for nice error handling in CLI), but I never did it after all.

I agree this is totally useless right now, and even harmful because of losing stacktrace, as you said. I would remove it, but it would introduce a breaking change in API 😞 To keep the backward-compatibility of the core API, instead of:

```ts
const wrapError = (err: Error) => {
  const error = new Error(`${err.name}: ${err.message}`);
  error.name = 'MongoSeedingError';
  return error;
};
```

I can refactor it to:

```ts
const wrapError = (err: Error) => {
  err.name = 'MongoSeedingError';
  err.message = `${err.name}: ${err.message}`
  return err;
};
```

In this way the original stacktrace will be kept. I know it's not beautiful, but still - I don't want to do breaking changes until 4.0.0. What do you think?

PS The code of Mongo Seeding would look different if I could rewrite the whole library from the scratch. It is planned for 4.0.0, but I don't know when it'll happen.

**Comment by ianwalter** [comment]
Yea, that sounds good. I don't even think you need to set the message property, but as long as the stacktrace is preserved I guess it doesn't really matter. Thanks!

**Comment by pkosiec** [comment]
> I don't even think you need to set the message property

I need to set it to keep the same message format as in current API version 🙂 

> As long as the stacktrace is preserved I guess it doesn't really matter.

Great, I will prepare a PR with the change soon. Cheers!
