### ISSUE TITLE
Adding zero documents into collection

### ISSUE THREAD

**Issue by vborshchov** [pkosiec/mongo-seeding#215]
Hello, and thank you for your incredible work.

In my current project, I'm using mongo-seeding to populate the database with seed data, employing a Docker image approach.

I intend to store my seed data in environment variables and pass them to the `docker run` command using the `--env-file=".env"` option.

However, I'm facing a challenge. I want to skip adding documents to the collection if an environment variable is not set. Currently, this results in an error: "Error MongoError [MongoSeedingError]: MongoSeedingError: Invalid Operation, no operations specified."

I'm unsure if this approach of using environment variables for data is the right one or if there's a way to handle the skipping of operations more gracefully.

Here's an example of my `.env` file:
```.env
FRUITS=[{"name": "Apple"},{"name": "Orange},{"name":"Banana"}]
```

My `docker` command looks like this:
```bash
docker run --rm --network="host" --env-file=".env" -e DB_PORT="27017" db-seed
```

And here's my Dockerfile:
```dockerfile
FROM ghcr.io/pkosiec/mongo-seeding:3.7.2

WORKDIR /data-import/

# Copy your project (import data and all dependencies have to be there)
COPY . /data-import/

# Install external dependencies
RUN npm install

# Set environmental variables (optional)

ENV DB_HOST host.docker.internal
ENV DB_NAME dev-db
ENV DB_PORT 272727
ENV DROP_DATABASE false
ENV DROP_COLLECTIONS true
ENV REPLACE_ID false
ENV SET_TIMESTAMPS false

WORKDIR /data-import/data

CMD seed
```

Any guidance on skipping operations based on environment variable settings or suggestions on a better approach would be greatly appreciated.

**Comment by pkosiec** [comment]
Hi @vborshchov,
Happy New Year! Thank you for your patience. Here are my thoughts/questions:
1. Just curious, why would you want to use environment variables instead of directory structure? What is your use case? For example, when using Mongo Seeding with integration tests, wouldn't it make sense to create a simple directory structure upfront, before running Mongo Seeding?
2. Mongo Seeding exits without an error if there are no collections detected for upload. Looks like you point to an non-empty directory, where there are some subdirectories with JSON files. See the code snippet: https://github.com/pkosiec/mongo-seeding/blob/main/core/src/populator/populator.ts#L50. Or, there's some bug which results in such problem 🤔 

Cheers!

**Comment by pkosiec** [comment]
Hey, it's been a while already. I'm closing the issue as I don't see anything actionable on the Mongo Seeding project for now. Feel free to comment the issue / create another one if you need more help related to Mongo Seeding. Cheers!
