### ISSUE TITLE
Connection string interpreted literally

### ISSUE THREAD

**Issue by murtyjones** [pkosiec/mongo-seeding#7]
First of all, great library! This is such a common use case that I can't believe there aren't go-to solutions out there. Hopefully this library becomes one.

I noticed that when using a connection string, e.g. `/test?retryWrites=true`, it should reference an existing database named `test` in mongo, but instead results in a new database being created with the name `/test?retryWrites=true`. Seems like the params from the `?` on are being interpreted literally. Don't know if it's an issue with this library or a dependency.

**Comment by pkosiec** [comment]
Hello @murtyjones,
Thank you for kind words! 
Yes, I confirm, this is a bug of `mongo-seeding`. I will try to fix it in a few hours and release a new version. I will let you know when I finish 🙂

**Comment by pkosiec** [comment]
I've fixed the error and updated dependencies, but unfortunately I cannot do the release right now because of the following issue: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26594
Can we wait a bit for a new release of mongo types? I think it will take one day at most. If this is urgent for you, then I can downgrade them and release new version.

Thanks for using mongo-seeding!

**Comment by murtyjones** [comment]
Thanks for the quick fix! In my case, `?retryWrites=true` wasn't needed so I just took it out.

**Comment by pkosiec** [comment]
Just a quick note: The new version of Mongo Seeding has been just released!
