### ISSUE TITLE
Generic type 'InsertWriteOpResult<TSchema>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by vivekb084** [pkosiec/mongo-seeding#91]
I am using mongo-seeding version 3.3 . When i am trying to build the project it is giving me below error

-**node_ts@1.0.0 serve /app
npm run build && tsc && node lib/server.js
node_ts@1.0.0 build /app
babel src --out-dir lib --extensions ".ts,.tsx"
Successfully compiled 85 files with Babel.
node_modules/mongo-seeding/dist/database/database.d.ts(19,94): error TS2314: Generic type 'InsertWriteOpResult' requires 1 type argument(s).**

One day ago everything was working fine . Without modifying any code i started to get this error.
I think it is saying we have to pass default type in Tschema.

**Comment by pkosiec** [comment]
Hi @vivekb084!
Did you recently upgraded `@types/mongodb` dependency in your app?

It looks like it is related to mismatch between MongoDB and MongoDB types. I've updated `mongodb` and `@types/mongodb` dependencies for `mongo-seeding` library, rerun `npm run build` and the output was different. Instead of:

```typescript
insertDocumentsIntoCollection(documentsToInsert: any[], collectionName: string): Promise<import("mongodb").InsertWriteOpResult>;
```
(as it is in mongo-seeding 3.3)

There is:

```typescript
insertDocumentsIntoCollection(documentsToInsert: any[], collectionName: string): Promise<import("mongodb").InsertWriteOpResult<Pick<any, string | number | symbol> & {
        _id: unknown;
    }>>;
```

(on master with all updated dependencies)

So, there are two possibilities:
- it is a Mongo Seeding bug (mismatch between `@types/mongodb` package and `mongodb` one)
- or you updated `@types/mongodb` dependency in your app

Anyway, I will update dependencies and release new version.

**Comment by pkosiec** [comment]
Hello again, @vivekb084! I've just published a new pre-release of Mongo Seeding, with updated `mongodb` TS types. Please try it out and tell me, if your issue has been resolved. Cheers!

**Comment by pkosiec** [comment]
I'm closing this issue as it should be resolved in the new release. If the issue still occurs, please leave a comment here, and I will reopen this thread.
